CREATE TABLE authorities (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50),
    authority VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id));
